SET ECHO ON 
DROP TABLE Computer CASCADE CONSTRAINTS;
DROP TABLE Operating_System CASCADE CONSTRAINTS;
DROP TABLE Manufacturer CASCADE CONSTRAINTS;
DROP TABLE Peripheral CASCADE CONSTRAINTS;
DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Purchased CASCADE CONSTRAINTS;
DROP TABLE Manufacturer_Region CASCADE CONSTRAINTS;
DROP TABLE Computer_Peripherals CASCADE CONSTRAINTS;
SET ECHO OFF
